//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TygerbergNeonatalAddin.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WardSpecimenTypeFilterExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["WardSpecimenTypeFilterExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["WardSpecimenTypeFilterExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UniqueLabNumberFilterExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["UniqueLabNumberFilterExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["UniqueLabNumberFilterExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ContaminantFilterExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["ContaminantFilterExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["ContaminantFilterExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NullFindingFilterExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["NullFindingFilterExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["NullFindingFilterExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OrganismGroupingExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["OrganismGroupingExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["OrganismGroupingExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimePeriodFilterExcludeFromApplyAllPreprocessing {
            get {
                return ((bool)(this["TimePeriodFilterExcludeFromApplyAllPreprocessing"]));
            }
            set {
                this["TimePeriodFilterExcludeFromApplyAllPreprocessing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WardColumnHeader {
            get {
                return ((string)(this["WardColumnHeader"]));
            }
            set {
                this["WardColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpecimenTypeColumnHeader {
            get {
                return ((string)(this["SpecimenTypeColumnHeader"]));
            }
            set {
                this["SpecimenTypeColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DesiredWards {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DesiredWards"]));
            }
            set {
                this["DesiredWards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection DesiredSpecimenTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DesiredSpecimenTypes"]));
            }
            set {
                this["DesiredSpecimenTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UniqueLabNumberFilterColumnHeader {
            get {
                return ((string)(this["UniqueLabNumberFilterColumnHeader"]));
            }
            set {
                this["UniqueLabNumberFilterColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContaminantFilterColumnHeader {
            get {
                return ((string)(this["ContaminantFilterColumnHeader"]));
            }
            set {
                this["ContaminantFilterColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ContaminantFilterValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ContaminantFilterValues"]));
            }
            set {
                this["ContaminantFilterValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NullFindingFilterColumnHeader {
            get {
                return ((string)(this["NullFindingFilterColumnHeader"]));
            }
            set {
                this["NullFindingFilterColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection NullFindingFilterValues {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NullFindingFilterValues"]));
            }
            set {
                this["NullFindingFilterValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OrganismGroupingColumnHeader {
            get {
                return ((string)(this["OrganismGroupingColumnHeader"]));
            }
            set {
                this["OrganismGroupingColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringDictionary OrganismGroupings {
            get {
                return ((global::System.Collections.Specialized.StringDictionary)(this["OrganismGroupings"]));
            }
            set {
                this["OrganismGroupings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimePeriodFilterPatientIdentificationColumnHeader {
            get {
                return ((string)(this["TimePeriodFilterPatientIdentificationColumnHeader"]));
            }
            set {
                this["TimePeriodFilterPatientIdentificationColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TimePeriodFilterDateColumnHeader {
            get {
                return ((string)(this["TimePeriodFilterDateColumnHeader"]));
            }
            set {
                this["TimePeriodFilterDateColumnHeader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public uint TimePeriodFilterNoDays {
            get {
                return ((uint)(this["TimePeriodFilterNoDays"]));
            }
            set {
                this["TimePeriodFilterNoDays"] = value;
            }
        }
    }
}
